[tool.poetry]
name = "basic-exercises"
version = "0.1.0"
description = ""
authors = ["Chaus <zoneofchaos@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
lorem = "^0.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
